### ISSUE TITLE
UI Bug: AI chat input text obscured by project selector and submit button

### ISSUE THREAD

**Issue by imramugh** [imramugh/ai_task_manager#6]
## Issue Description
When typing in the AI chat interface, the input text gets obscured by the project selector button and the submit button, making it difficult to see what you're typing.

## Current Behavior
- Text input extends behind the project selector button (e.g., "SDLC Modernization")
- The end of the text is hidden by the arrow/submit button
- Users cannot see the full text they're typing

## Screenshots
As shown in the provided screenshots:
- First image: Text "...to accelerate" is partially hidden
- Second image: Text gets cut off at "SD" 

## Expected Behavior
- Input text should have proper padding/margin to avoid being hidden by buttons
- The entire typed message should be visible
- Text input area should respect the space occupied by the project selector and submit button

## Suggested Fix
```css
/* Add padding to the input field to account for the buttons */
.chat-input {
  padding-right: 200px; /* Adjust based on actual button widths */
}

/* Or use a flex layout approach */
.chat-input-container {
  display: flex;
  align-items: center;
  gap: 8px;
}

.chat-input {
  flex: 1;
  /* Remove any absolute positioning that might cause overlap */
}
```

## Alternative Solutions
1. Move the project selector outside of the input field area
2. Place the project selector above or below the input field
3. Use a more compact project selector design
4. Implement a floating label pattern that moves out of the way

## Testing Notes
- Test with long messages
- Test on different screen sizes
- Ensure the fix works with different project name lengths
- Verify keyboard navigation still works properly
